# Generated by Django 3.2.18 on 2023-04-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
