# Generated by Django 3.2.18 on 2023-04-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenge', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.TextField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('tir_media', models.IntegerField()),
                ('total_captado', models.IntegerField()),
                ('vgv', models.IntegerField()),
            ],
        ),
    ]
