# Generated by Django 3.2.18 on 2023-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenge', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tir_media',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_captado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='vgv',
            field=models.IntegerField(null=True),
        ),
    ]
